Repository snu-quiqcl/artiq-proxy, pull requests merged in 2023-08, with the labels that each got.

#43 Change the deprecated `.dict()` to `.model_dump()`
  test.py
Labels: bug, test

#40 Support the visualization option in submission
  config.json
  main.py
Labels: enhancement

#46 A `scheduler` replica
  main.py
Labels: enhancement

#48 Fetch the running experiment RID
  main.py
Labels: enhancement

#41 Make an experiment fetcher
  main.py
Labels: enhancement

#54 Unit test for scheduler-related proxy request
  main.py
  test.py
Labels: test
