Repository snu-quiqcl/artiq-proxy, pull requests merged in 2023-10, with the labels that each got.

#80 Set the default profile of a specific DDS
  config.json
  main.py
Labels: enhancement

#83 Turn on and off TTL switch of a specific DDS
  main.py
Labels: enhancement

#84 Set the attenuation of a specific DDS
  main.py
Labels: enhancement

#86 Fix that fetching the scheduled queue works wrong
  main.py
  test.py
Labels: bug

#88 `DatasetTracker`
  dataset.py
Labels: enhancement

#90 Subscribe dataset modification
  config.json
  dataset.py
  main.py
  test.py
Labels: enhancement

#92 Track last deletion timestamps
  dataset.py
Labels: enhancement

#94 Long polling for `get_dataset_modification()`
  dataset.py
  main.py
Labels: enhancement

#95 Return timestamp with the dataset
  main.py
Labels: enhancement

#96 Get from local dataset
  dataset.py
  main.py
Labels: enhancement

#98 Resolve `FileNotFoundError` when fetching result directory
  main.py
Labels: bug

#99 Use built-in type annotation
  dataset.py
  main.py
Labels: style
