Repository snu-quiqcl/artiq-proxy, pull requests merged in 2023-09, with the labels that each got.

#58 Remove Python 3.8
  .github/workflows/pylint.yml
  .github/workflows/unittest.yml
Labels: repository

#59 Send the result directory structure
  .github/workflows/pylint.yml
  .github/workflows/unittest.yml
  main.py
Labels: enhancement

#62 Send H5 format result file, code, and vcd file of the specific RID
  main.py
Labels: enhancement

#67 Set the override and level option of a specific TTL
  .github/workflows/pylint.yml
  .github/workflows/unittest.yml
  config.json
  main.py
  test.py
Labels: enhancement

#65 Skip the unittest about submission temporarily
  test.py
Labels: test

#71 Set the voltage of a specific DAC
  config.json
  main.py
Labels: enhancement

#72 Read master dataset
  main.py
Labels: enhancement

#74 Fix the experiment code to set DAC voltage
  main.py
Labels: bug

#76 Use TTL name to set the override and level
  config.json
  main.py
  test.py
Labels: enhancement
